[package]
name = "ad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = true
lto = true

[[bench]]
name = "bench_main"
harness = false

[dependencies]
bitflags = "2.4.1"
libc = "0.2.148"

[dev-dependencies]
simple_test_case = "1.1.0"
criterion = "0.5"
